name: miscelaneos
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  compassx: ^1.0.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.5.0
  flutter_riverpod: ^2.6.1
  geolocator: ^14.0.2
  go_router: ^15.2.4
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.12.3
  google_mobile_ads: ^6.0.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  local_auth: ^2.3.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  quick_actions: ^1.1.0
  sensors_plus: ^6.1.1
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  workmanager: ^0.8.0

dev_dependencies:
  build_runner: ^2.4.13
  change_app_package_name: ^1.5.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/compass/
