name: miscelaneos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  compassx: ^1.0.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  geolocator: ^14.0.2
  go_router: ^15.2.4
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.12.3
  local_auth: ^2.3.0
  permission_handler: ^12.0.0+1
  quick_actions: ^1.1.0
  sensors_plus: ^6.1.1
  share_plus: ^11.0.0

dev_dependencies:
  change_app_package_name: ^1.5.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/compass/
